name: Test Project

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache-dependency-path: ./second-action-react/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./second-action-react

      - name: Run Tests
        run: npm test
        working-directory: ./second-action-react

