name: Test Project

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Download a copy of the code in your repository.
      - name: Get Code
        uses: actions/checkout@v4
      # Set up Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache-dependency-path: ./second-action-react/package-lock.json
      # Install Dependencies
      - name: Install Dependencies
        run: npm ci
        working-directory: ./second-action-react
      # Run Tests
      - name: Run Tests
        run: npm test
        working-directory: ./second-action-react

  deploy:
    # We build dependencies in the deploy job with a keyword `needs`.
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Download a copy of the code in your repository.
      - name: Get Code
        uses: actions/checkout@v4
      # Set up Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache-dependency-path: ./second-action-react/package-lock.json
      # Install Dependencies
      - name: Install Dependencies
        run: npm ci
        working-directory: ./second-action-react
      # Build
      - name: Build Project
        run: npm run build
        working-directory: ./second-action-react
      # Deploy
      - name: Deploy
        run: echo "Deploying..."


